agrego api para obtener número random
reactbuenosaires/website pull request #9
Opened 2023-10-26 02:58 UTC by loveragabriel

- Creo file para consultar la url de random.org para obtener número random y paso como parametro el valor máximo a consultar 
- ajusto componente random y agrego: 
 -useEffect para manejar las consultas de la api y que no se genere un loop al momento de obtener el numero random ganador.
 -paso como argumento el número obtenido del input con la cantidad de participantes. 
 -agrego un useState que maneja el estilo del input cuando se clickea el boton generar y no hay numeros en el input ( lo que generar un border amarillo de "alerta"). 
 -agrego tag span que dice Ganador/a para que aparezca con el número random obtenido.

2023-10-26 03:07 UTC, naniitevez commented on src/app/giveaways/random/page.jsx
>  "use client";
Mover todo lo que sea interactivo y client side, a un componente (o los que sean necesarios). Que la page no tenga esta linea de "use client".

2023-10-26 03:11 UTC, naniitevez commented on src/utils/radom.js
Usa un nombre mas declarativo para el archivo, podría ser el mismo nombre que la función que guarda

2023-10-26 03:12 UTC, naniitevez commented on src/app/giveaways/random/page.jsx
> +  useEffect(() => {}, [winner]);
Por qué está el use effect vacío?

Sería mejor que dentro se ejecutara la funcion getRandomNumber()

2023-10-26 03:14 UTC, naniitevez commented on src/app/giveaways/random/page.jsx
> +          className={inputClass}
Sería mejor deshabilitar el botón de generar número para cuando el input esté vacío, en vez de hacer esta movida para mostrar el borde amarillo en el input.

2023-10-26 03:16 UTC, naniitevez commented on src/app/giveaways/random/page.jsx
> +  const generateRandom = () => {
Quizás esta lógica se pueda simplificar (o eliminar) cuando modifiques el funcionamiento del useEffect

2023-10-26 03:17 UTC, naniitevez commented on src/app/giveaways/random/page.jsx
> +  const generateRandom = () => {
No termino de entender la lógica de esto

2023-10-26 03:39 UTC, loveragabriel commented on src/utils/radom.js
actualizo nombre del archivo

2023-10-27 03:24 UTC, loveragabriel commented on src/app/giveaways/random/page.jsx
>  "use client";
Creé un nuevo componente que maneja toda la interacción de random y luego lo paso dentro del componente page.

2023-10-27 03:25 UTC, loveragabriel commented on src/app/giveaways/random/page.jsx
> +  useEffect(() => {}, [winner]);
Había agredado el useEffect para evitar un loop al momento de llamar la función generateRandom. Ahora Eliminé el useEffect y la función se ejecuta sin problemas ahora.

2023-10-27 03:29 UTC, loveragabriel commented on src/app/giveaways/random/page.jsx
> +          className={inputClass}
Ajusto esta funcionalidad y agrego la propiedad disabled. A través de un useState se maneja los valores true y false.

2023-10-27 03:30 UTC, loveragabriel commented on src/app/giveaways/random/page.jsx
> +  const generateRandom = () => {
Esta parte del código estaba eliminada. Yo no es se muestra en el componente.

2023-10-28 13:57 UTC, naniitevez requested changes
De jodida, te pido los últimos cambios. 
Excelente trabajo 💪

2023-10-28 13:57 UTC, naniitevez commented on src/app/giveaways/random/interactive.jsx
> +  const [maxInputNumner, setMaxInputNumner] = useState("");
Fijate que no dice number

2023-10-28 13:57 UTC, naniitevez commented on src/app/giveaways/random/interactive.jsx
> +        disabled={isButtonDisabled}
Acá podrías reutilizar la variable que guarda el valor del input de participantes, si está vacío el botón se deshabilita, sino se habilita. Y te ahorras el crear un state para manejar eso.

`disabled={maxInputNumner === 0 ? true : false}`

2023-10-28 13:57 UTC, naniitevez commented on src/app/giveaways/random/interactive.jsx
> +  const [maxInputNumner, setMaxInputNumner] = useState("");
Podrías probar con guardar un número en este estado, y no un string. Para poder hacer la validación que menciono en un comentario más abajo (para el disabled del button) un poco más limpia.

Para esto deberías también verificar que el input reciba solo números agregandole el type.

`disabled={maxInputNumner === 0 ? true : false}`

2023-10-28 13:57 UTC, naniitevez commented on src/app/giveaways/random/interactive.jsx
> +  const [maxInputNumner, setMaxInputNumner] = useState("");
El ganador también debería ser un número y no un string. 

Cuando creas el estado, pasale el valor 0 como inicializador y no "".

Por ejemplo: `const [maxInputNumner, setMaxInputNumner] = useState(0);`

2023-10-29 02:12 UTC, loveragabriel commented on src/app/giveaways/random/interactive.jsx
> +  const [maxInputNumner, setMaxInputNumner] = useState("");
1. Ajusto valor y nombre del estado maxInputNumber
2. verifico que el input tenga type='number' (ok)
3. El estado de ganador lo dejé vacio, para que el ternario no lo muestre en pantalla y no agregar más validaciones.  (winner && maxInputNumber &&)

2023-10-29 02:13 UTC, loveragabriel commented on src/app/giveaways/random/interactive.jsx
> +        disabled={isButtonDisabled}
Agrego ternario de la siguiente manera:{!maxInputNumber || maxInputNumber <= 0 ? true : false}. Le agregué que sea diferente de 0 e igual o  menor a cero, porque si escribía algun numero y luego lo borraba, quedaba el boton para generar random habilitado. De esta menera solo se habilita el boton cuando hay un numero mayor a 0.

2023-10-29 02:16 UTC, loveragabriel commented
Consulta: Tenemos algunos componentes creados con export default function y otros creados con const Name =()=>. 
Esto tendríamos que ajustarlos a una sola forma correcto?
Por otro lado cuál sería la forma correcta, porque veo que Nextsj lo tiene como cont Name =()=>
![image](https://github.com/reactbuenosaires/website/assets/87627423/95f1e263-6fd3-476a-8fa2-a94061b48ad8)

2023-10-31 12:40 UTC, naniitevez commented
> Consulta: Tenemos algunos componentes creados con export default function y otros creados con const Name =()=>. Esto tendríamos que ajustarlos a una sola forma correcto? Por otro lado cuál sería la forma correcta, porque veo que Nextsj lo tiene como cont Name =()=> ![image](https://user-images.githubusercontent.com/87627423/278847487-95f1e263-6fd3-476a-8fa2-a94061b48ad8.png)

En la práctica, la diferencia es un poco insignificante, entre una forma u otra de tener definidas y exportadas las funciones. 

Según tengo entendido la cosa es que al tenerla exportada así: `export default function miFuncion() {}` la estás exportando inmediatamente en su definición  para usarla en otros archivos.

Y al tenerla declarada así: `const miFuncion = () => {}` y exportada al final del archivo (`export default miFuncion;`) lo que haces es definirla primero y la función no va a estar disponible hasta que todo el código haya sido ejecutado. Esto es útil por ejemplo si tenes código adicional en el archivo que se ejecute antes de que la función este disponible para importación. 

Por el momento, no le daría mucha importancia a ese cambio.

2023-10-31 12:40 UTC, naniitevez approved these changes

2023-10-31 12:41 UTC, merged